### ISSUE TITLE
Licensing concerns

### ISSUE THREAD

**Issue by djc** [rust-iendo/yarte#5] opened 2019-02-20 13:28 UTC
It looks to me like yarte was basically started by copying code from Askama and then changing it -- the structure of the code is extremely similar. This is mostly fine, except for one thing: Askama does not seem to be mentioned anywhere in the README or elsewhere (except for one comment pointing to Askama's source code), and this is not allowed under Askama's license terms, which say (MIT):

> The above copyright notice and this permission notice
> shall be included in all copies or substantial portions
> of the Software.

or, if you want to license Askama under the Apache license, there's a longer list of applicable requirements in section 4.

Please look into this situation.

**Comment by botika** [comment] 2019-02-20 14:20
I do not understand about licenses, I understand the code. 
You are free to do the pull request. 
I the first issue about licensing, what's wrong with this, yarte is going to have a license: start programming.

**Comment by djc** [comment] 2019-02-20 14:24
Sorry, I'm not going to fix this for you -- this is your project. If you want to run your own project, you'll have to at least comply with the minimum of standards.

**Comment by rakenodiax** [comment] 2019-02-20 15:15
Like it or not, understanding licensing *is* an important aspect of programming, especially when deciding to create your own open source project. If this issue isn't addressed, there may be ramifications for users of this project, as well.

I personally see licensing issues as a big red flag when evaluating libraries for my own projects, and I'd be surprised if this weren't a commonly held stance in your target audience of users.

@djc et. al were generous enough to release `askama` under a very permissive open source license for the whole world to use, giving them the proper credit is the least one can do.

**Comment by botika** [comment] 2019-02-20 16:09
I'm working, I'm not going to waste my time with this. Look at the commits logs and tell yourself if you want to go through the Patreon. You can fork, sell, traffic, give away my code, ... and to be otherwise we should all to Euler.

 And that's all I have to say about licenses, that you can launch a `cargo bench` and a `diff -r`.

**Comment by swfsql** [comment] 2019-02-20 17:39
Just a personal opinion:

I also dislike licenses, both copyright and copyleft ones since both depends on intellectual property, which is a form of aggression.

That being said, it's a "honesty trait" exposure opportunity to acknowledge important and meaningful references, even disconsidering licensing. 
Licensing itself facilitates that others will incorporate your projects in the future.

But I agree, unfortunately copyleft/right exist (are imposed) which prejudice creativity.
So I hope you will change your mind regarding this bureocracy at some point.

**Comment by rakenodiax** [comment] 2019-02-20 17:50
If this project were to be taking a stance on licensing "on principle" in this matter, they should use Unlicense+MIT or something similar, but hey, the licensing was also copied from Askama

**Comment by icefoxen** [comment] 2019-02-20 21:04
If the creator of this project doesn't want to offer proper attribution to the people whose work he is using without giving credit for it, then there are [ways to deal with it](https://support.patreon.com/hc/en-us/articles/208377833-How-do-I-send-a-DMCA-takedown-notice-).

Yes, it's awful.  I don't really expect djc to do it.  But at some point one has to be responsible for their actions even when it's unpleasant.

**Comment by phaazon** [comment] 2019-02-21 11:21
I highly suggest @djc to bring the FSF’s attention on this issue. Looks like @botika doesn’t know how to behave as a respectful human being and clearly doesn’t care about the work of others. They were pointed, several times, to the correct procedure to follow. They rejected it and on top of that, went full ballistic.

When you “only understand code” and don’t understand the implication of using someone’s else work, you should accept the fact that you’re violating a copyleft and are now exposed to any applicable sanctions (I suggest you lookup on Google, sanctions have already been applied to people like you who don’t care about others’ work).

**Comment by djc** [comment] 2019-02-21 13:26
I'm quite disappointed in the author's stance on this issue, but as long as yarte isn't very successful, I'm not interested in chasing this down. I have revoked @botika's Collaborator-level access to Askama, though.

**Comment by Lucretiel** [comment] 2019-02-22 02:50
Wow. I was curious about this project but the cavalier stance toward licensing and good-faith attribution is a major turn off. I'll be sure to stay away in the future.

**Comment by botika** [comment] 2019-02-23 11:27
And to continue with the joke, because I already enjoy it. Among all this, has anyone read the code? Can you link the parts of the code that violate the license?

**Comment by botika** [comment] 2019-02-23 13:04
I need the code, file and line parts of the project that violate one of the two licenses, MIT and APACHE, on which the rights as author are based. You can give me the links or raise an issue. Thank you very much for your time.

**Comment by Havvy** [comment] 2019-02-23 13:09
All or a majority of the test files in the initial commit are copies from the Askama project. The Template trait is 2/3rds equivalent including the exact wording and punctuation of comments. The yarte_config/templates directory is a copy of askima_shared/templates. 

https://github.com/rust-iendo/yarte/commit/8a6cb06d8e0a39a337e9030a5daff8b3b809d17a#diff-8f1bd1269b2ecba09fd9c1e3564d6b8fR140 is https://github.com/djc/askama/blob/master/askama_derive/src/generator.rs#L262

And I'm going to stop looking there.

There's so much little things spread around that it's clear that this is a fork of Askima and as such, following the licensing for Askima is imperative.

**Comment by botika** [comment] 2019-02-23 13:20
I can redo the initial commit if you feel more comfortable. Please use some differencing tool here I do not see anything. Please, you can use the unix `diff -ru` command as this [man](http://man7.org/linux/man-pages/man1/diff.1.html) shows.
Thanks for you time.

**Comment by djc** [comment] 2019-02-23 18:41
You can spend a lot of time obfuscating that yarte is a direct descendant of Askama, but that doesn't change the fact that yarte is a derived work. I don't understand why you don't simply add a copy of the MIT license with my name in it, a mention in the README that this is a fork from Askama, and then the project is compliant.

**Comment by phaazon** [comment] 2019-02-23 19:30
I admire you for your patience @djc.

**Comment by botika** [comment] 2019-02-23 20:28
This is an issue, of a repository. Please, if you have any opinion, reserve it for whoever cares. . Simply the `diff -r` return a very high percentage of difference. Links please, documents that justify something.

**Comment by Lucretiel** [comment] 2019-02-23 21:21
It's deeply concerning that you're rewriting files, renaming and refactoring things in what appears to be an attempt to make this project sufficiently different to Askana that it's no longer considered a fork. That's not at all how it works. The issue is not that the code is similar to Askana. The issue is that this is plainly a fork of Askana.

You asked for documents that justify something. This is the [license](https://github.com/djc/askama/blob/master/LICENSE-MIT) of the project whose code you're using. I've excerpted the relevant passage:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
> 
> **The above copyright notice and this permission notice
shall be included in all copies or substantial portions
of the Software.** [emphasis added]

**Comment by botika** [comment] 2019-02-23 21:50
I have not modified it, I have deleted it completely and I have made it whole again. There is no entry that says any of that. Please look at the code before and provide evidence, such file such line is equal to such file such line and I refactor the concept so that it can not be considered a fork

**Comment by Lucretiel** [comment] 2019-02-23 21:53
I really don't understand what the disconnect here is. You stated [here](https://www.reddit.com/r/rust/comments/asenye/yarte_yet_another_rust_template_engine_is_the/eh16lqt/) that Yarte is a modified copy of Askama. It is plain from your interactions in that reddit thread and this github thread that Yarte is a modified version of Askama.

**Comment by botika** [comment] 2019-02-23 22:05
I said that I was the greatest collaborator, never that I was a fork. That it was normal for my code to resemble that of askama because it was the same, the same because **I do it**. It was not thought that in google they were teaching to look at the code before opening their mouths.

**Comment by Lucretiel** [comment] 2019-02-23 22:10
The fact that you're a contributor to Askama also does not relieve you of your obligations under the License.

**Comment by botika** [comment] 2019-02-23 22:53
I'm sorry my English is not very good and the google translator does not help. That if I write 2 codes are similar, right? Well, if I have written both, it is normal that they look alike. All good? that's what I was trying to say.

Because when you are in reddit you are not programming.

travis is about to finish. some file and line?

**Comment by Lucretiel** [comment] 2019-02-23 23:23
Just to be clear, you are now claiming that you are the owner of Askama, not @djc? That you wrote all of it? That's the only way your claims have merit. Otherwise, the fact that you contributed code to Askama does not relieve you of your obligations under the license to him as the copyright holder.

**Comment by botika** [comment] 2019-02-23 23:26
Okay, I did not say that either. Please, check the code and compare. Understand ?

**Comment by Lucretiel** [comment] 2019-02-23 23:28
Or, is the claim that you wrote yarte FROM SCRATCH and it just so happened that all of the structure and class names and function names and project structure and dual MIT/Apache license was coincidental? Even though you have also previously [stated](https://www.reddit.com/r/rust/comments/asenye/yarte_yet_another_rust_template_engine_is_the/eh16lqt/) that "Yes of course it is a copy".

The fact that your version is faster has no bearing on whether this is a modified copy.
The fact that you have gone through and tried to rename every single function and struct has no bearing on whether this is a modified copy.

**Comment by Lucretiel** [comment] 2019-02-23 23:29
You seem to think that if I give you an itemized list of lines of code that are the same between Askama and yarte, all you have to do is edit those lines, and you're free from you obligations under the license. This is wrong, plain and simple.

**Comment by botika** [comment] 2019-02-24 01:27
Not one of the current yarte functionalities uses the current or later askama code in any way. In functionality none is the same. That is, even if they have the same name, you can link me to the yarte functionalities that resemble those of askama. The parser? the generator? the respective visits? the documentation sheet? the structure of the trait? the implementation of the actix response? etc that is exactly what is the same?

Because in my opinion you have not bothered to read the code. I do not think that for some engineers of your experience it costs so much to copy and paste two links to github.

**Comment by Lucretiel** [comment] 2019-02-24 01:42
Also irrelevant. In any case, we can all see the commits you're making where you rename and restructure the code so that it looks less like Askama. Even if you go through and erase the project history, I have a clone of your repo to preserve all those edits. I bet that if I did a diff of your initial commit against Askama it'd look pretty similar.

Here's what you said farther up in the thread:

> 6 days here bothering, but you are still painting from the io::Write, you can not share scope father son in the same stack, how are you going to refactor that generator to allow continuous writing? How are you going to look for each expression of rust with the 1000 lines? Are you going to read the move of a closure byte to byte? And you are still here without knowing what is missing?

You appear to have an intimate knowledge of all the ways that yarte differs from Askama, because yart is a copy of Askama that you modified and refactored.

**Comment by Lucretiel** [comment] 2019-02-24 01:44
I'll also go ahead and link the side-by-side version of yatre's Cargo.toml and Askama's Cargo.toml. It's plainly the same file with minor edits: https://imgur.com/a/szxcQnD

**Comment by botika** [comment] 2019-02-24 13:39
There is no argument backed by something real.

## Example of something real:
In the file `yarte/../...rs` **lines i-j** is the same of the file `askama/../...rs` **lines i1-j1**. Therefore ...



## I will close it in the next day. Please include in your answers, issues or pull request a valid link to github.

**Comment by botika** [comment] 2019-02-24 14:04
Thanks to all, yesterday I made this visit with [all your support](https://github.com/rust-iendo/yarte/blob/master/yarte_derive/src/generator/visit_derive.rs). You can copy it if you want to make a visit with about a derive. thanks again. 

You can thank Leonard Euler, Henri Poincaré and especial to [Jacques Hadamard](https://en.wikipedia.org/wiki/Jacques_Hadamard) in the README. 

I hope they improve as engineers with my code as I did with all the previous one.

**Comment by swfsql** [comment] 2019-02-24 14:06
Another personal input:  
For me it seems that, on your perspective, @botika, a project to be a fork diminishes such fork project.  
It diminishes any work that anyone (yourself) has done on such fork.

It doesn't.

You are constantly defending the idea that you've put your own work and time into it.  
Not a single user has denied that, and also not even suggested that they do.

**Comment by botika** [comment] 2019-02-24 14:07
## Example of something real:
In the file `yarte/../...rs` **lines i-j** is the same of the file `askama/../...rs` **lines i1-j1**. Therefore ...

Your opinion is not scientific, please. I think it's very easy to understand that it's not a forum, it's an issue.

**Comment by botika** [comment] 2019-02-24 16:32
You have already managed to compare the carriage with the Tesla, if both have 4 wheels we are going to give you their part. 

### To everyone who has contributed to this please **do not use** yarte

i close

**Closed by botika** 2019-02-24 16:32 UTC
Labels: bug

**Comment by bkfox** [comment] 2019-02-25 00:56
Well don't worry, I think that this is at least clear that nobody would want to use "yarte" after reading this issue.
I've just also check a bit the code, cauz' you insisted so much, that I couldn't help myself. Random file: `testing/tests/actix_web.rs` in both project ( https://github.com/djc/askama/blob/master/testing/tests/actix_web.rs ; and here in your initial commit: https://github.com/rust-iendo/yarte/commit/8a6cb06d8e0a39a337e9030a5daff8b3b809d17a ), function `test_actix_web()`.

The best you can do is to act as an adult and admit your fault (lets say "error" if you prefer), and respect original Askama's license.

----
Bueno, no te preocupes, creo que esto está claro, al menos que nadie querría usar "yarte" después de leer este discusion. Yo reviso un poco del codigo, y si tomo un archivo aleatorio: `testing/tests/actix_web.rs` en ambos proyectos (https://github.com/djc/askama/blob/master/testing/tests/actix_web.rs; y aquí en su confirmación inicial: https: // github .com / rust-iendo / yarte / commit / 8a6cb06d8e0a39a337e9030a5daff8b3b809d17a), función `test_actix_web ()`.

Lo mejor que puede hacer es ir a un adulto y admitir su culpa (digamos "error" si lo prefiere), y respectar la licensia original de Askama.

**Comment by phaazon** [comment] 2019-02-25 09:14
What are they going to answer to that? Are they going to destroy the whole commit history to obfuscate even further? Should I make screenshots or even clone the current repository?! So much gossip!

![](https://media.giphy.com/media/nWg4h2IK6jYRO/giphy.gif)
